apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontdeskai
  labels:
    app: frontdeskai
spec:
  selector:
    matchLabels:
      app: frontdeskai
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
